import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen max-w-[950px] bg-slate-400 text-black">
        {children}
      </body>
    </html>
  );
}
